services:
#    BpolNet\Bundle\LangleyBundle\Command\LangleyDumpCommand:
#        public: true
#        arguments:
#            - '@BpolNet\Bundle\LangleyBundle\Service\Langley'
#        tags:
#            - { name: 'console.command', command: 'langley:dump' }

    Imigio\Service\ImigioClient:
        autowire: false
        arguments:
            - '@?'
