services:
#    BpolNet\Bundle\LangleyBundle\Command\LangleyDumpCommand:
#        public: true
#        arguments:
#            - '@BpolNet\Bundle\LangleyBundle\Service\Langley'
#        tags:
#            - { name: 'console.command', command: 'langley:dump' }
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $imigioProjectCname: '%imigioProjectCname%'

    Imigio\Action\:
        resource: '../../Action'
        tags: [ 'controller.service_arguments' ]

    Imigio\Service\ImigioClient:
        autowire: false
        arguments:
            - '@?'
    Imigio\Twig\TwigImigioExtension:
#        autowire: true
#        autoconfigure: true
        tags:
            - { name: twig.extension }

    Imigio\Service\ImigioRouteGenerator: ~
    Imigio\Service\ImigioRelationMapping: ~
