services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $imigioProjectCname: '%imigioProjectCname%'
            $imigioPlaceholder: '%imigioPlaceholder%'

    Imigio\Action\:
        resource: '../../Action'
        tags: [ 'controller.service_arguments' ]

    Imigio\Service\ImigioClient:
        autowire: false
        arguments:
            - '@?'
    Imigio\Twig\TwigImigioExtension:
        tags:
            - { name: twig.extension }

    Imigio\Service\ImigioRouteGenerator: ~
    Imigio\Service\ImigioRelationMapping: ~
